#!/usr/bin/bash

a=$("$HOME/Projects/cdd/target/release/supercd" "$@")

if [[ $a == "@"* ]] ;
then
	cd "${a:2}" || exit 1
else
	IFS=';' read -r lines <<< "$a"
    for i in $(echo "$lines" | sed 's/ //g' | sed 's/;/\n/g')
	do
        echo "$(echo "$i" | sed 's/=/ = /g')"
	done
fi
